# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_school_school_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rest_place',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rest_time',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
