# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_meal_meal_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_logo',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
