# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_school_school_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_time',
            field=models.CharField(choices=[('조식', '조식'), ('중식', '중식'), ('석식', '석식'), ('상시', '상시')], max_length=100),
        ),
    ]
