# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_school_school_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_short',
            field=models.CharField(max_length=20),
        ),
    ]
