# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20170126_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='school_short',
        ),
    ]
