# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_remove_school_school_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_short',
            field=models.CharField(default='', max_length=10),
        ),
    ]
