# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_school_school_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='rest_place',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='rest_time',
        ),
        migrations.RemoveField(
            model_name='school',
            name='id',
        ),
        migrations.AlterField(
            model_name='school',
            name='school_short',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
    ]
